name: "Authenticate with GCP"
description: "Authenticate with GCP using the credentials JSON file"
inputs:
  credentials_file:
    description: "Base64 encoded JSON credentials file"
    required: true
  debug:
    description: "Toggle debug mode on/off"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Create credentials file
      shell: bash
      run: |
        mkdir -p "$HOME/.config/gcloud"
        ls -la -R "$HOME/.config"
        echo "${{ inputs.credentials_file }}" | base64 -d > "$HOME/.config/gcloud/application_default_credentials.json"
        echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/.config/gcloud/application_default_credentials.json" >> "$GITHUB_ENV"

    - name: Authenticate With Google Cloud
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ inputs.credentials_file }}

    - name: Setup gcloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: latest

    - name: Debug Auth Files
      shell: bash
      if: inputs.debug == 'true'
      run: |
        cat "$HOME/.config/gcloud/application_default_credentials.json"
