name: Setup Secret Files
description: "Decodes and writes secret files based on passed dynamic prefix"

inputs:
  secrets:
    description: Secrets from Main Repository (JSON Format)
    required: true
  prefix:
    description: "Prefix to prepend to secret name"
    required: true
  suffix:
    description: "Suffix to append to secret name"
    required: true
  filename:
    description: "Filename to create"
    required: true

runs:
  using: composite
  steps:
    - name: Construct Secret Name
      shell: bash
      run: |
        PREFIX=$(echo "${{ inputs.prefix }}" | tr '[:lower:]' '[:upper:]')
        SUFFIX=$(echo "${{ inputs.suffix }}" | tr '[:lower:]' '[:upper:]')

        echo "SECRET_NAME=${PREFIX}${SUFFIX}" >> $GITHUB_ENV

    - name: Write Secret File
      shell: bash
      run: |
        SECRET_VALUE=$(echo '${{ inputs.secrets }}' | jq --raw-output ".${{ env.SECRET_NAME }}")
        echo "$SECRET_VALUE" | base64 -d > "${{ inputs.filename }}"
