name: "Discord Deployment Notification"
description: "Send a message to Discord channel"

inputs:
  discord_webhook:
    description: "Discord Webhook To Authenticate Sender"
    required: true
  message:
    description: "Message to send!"
    required: true

runs:
  using: composite
  steps:
    - name: Send Discord Notification
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ inputs.DISCORD_WEBHOOK }}
      with:
        args: ${{ inputs.MESSAGE }}
