name: "Discord Deployment Notification"
description: "Send a message to Discord channel with flexible embed support"
inputs:
  discord_webhook:
    description: "Base64 Encoded Discord Webhook To Authenticate Sender"
    required: true
  message:
    description: "Message to send!"
    required: false
    default: ""
  embed_template:
    description: "Discord embed template with placeholders"
    required: false
    default: ""
  embed_title:
    description: "Title for the embed"
    required: false
    default: "Notification"
  embed_color:
    description: "Color for the embed (decimal)"
    required: false
    default: "3066993"
  embed_fields:
    description: "JSON array of fields for the embed"
    required: false
    default: "[]"
  service_name:
    description: "Service name for footer"
    required: false
    default: "Service"

runs:
  using: composite
  steps:
    - name: Validate Conflicted Fields Inputs
      if: inputs.embed_template != '' && inputs.message != ''
      shell: bash
      run: echo "::error::Cannot provide both 'embed_template' and 'message', Choose one!" && exit 1

    - name: Validate Required Inputs
      if: inputs.embed_template == '' && inputs.message == ''
      shell: bash
      run: echo "::error::Either 'message' or 'embed_template' is required" && exit 1

    - name: Decode Webhook
      shell: bash
      id: discord
      run: echo "DISCORD_WEBHOOK=$(echo "${{ inputs.discord_webhook }}" | base64 -d)" >> "$GITHUB_OUTPUT"

    - name: Process Embed Template
      if: inputs.embed_template != ''
      shell: bash
      id: embed
      run: |
        FINAL_JSON="${{ inputs.embed_template }}"
        FINAL_JSON="${FINAL_JSON//\{\{TITLE\}\}/${{ inputs.embed_title }}}"
        FINAL_JSON="${FINAL_JSON//\{\{COLOR\}\}/${{ inputs.embed_color }}}"
        FINAL_JSON="${FINAL_JSON//\{\{SERVICE_NAME\}\}/${{ inputs.service_name }}}"
        FINAL_JSON="${FINAL_JSON//\{\{FIELDS\}\}/${{ inputs.embed_fields }}}"
        echo "PROCESSED_EMBED=$FINAL_JSON" >> "$GITHUB_OUTPUT"

    - name: Send Discord Message Using Embed Templates
      if: inputs.embed_template != ''
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ steps.discord.outputs.DISCORD_WEBHOOK }}
        DISCORD_EMBEDS: ${{ steps.embed.outputs.PROCESSED_EMBED }}

    - name: Send Discord Message
      if: inputs.message != ''
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ steps.discord.outputs.DISCORD_WEBHOOK }}
      with:
        args: |
          ======== MESSAGE START ========
          ${{ inputs.message }}
          ========  MESSAGE END  ========
