name: "Discord Deployment Notification"
description: "Send a message to Discord channel"

inputs:
  discord_webhook:
    description: "Base64 Encoded Discord Webhook To Authenticate Sender"
    required: true
  message:
    description: "Message to send!"
    required: true

runs:
  using: composite
  steps:
    - name: Decode Webhook
      shell: bash
      id: discord
      run: echo "DISCORD_WEBHOOK=$(echo "${{ inputs.discord_webhook }}" | base64 -d)" >> "$GITHUB_OUTPUT"

    - name: Send Discord Notification
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ steps.discord.outputs.DISCORD_WEBHOOK }}
      with:
        args: |
          ${{ inputs.MESSAGE }}

          ==============================
