name: "Discord Deployment Notification"
description: "Send a message to Discord channel with flexible embed support"
inputs:
  discord_webhook:
    description: "Base64 Encoded Discord Webhook To Authenticate Sender"
    required: true
  message:
    description: "Message to send!"
    required: false
    default: ""
  embed_template:
    description: "Discord embed template with placeholders"
    required: false
    default: ""
  embed_title:
    description: "Title for the embed"
    required: false
    default: "Notification"
  embed_color:
    description: "Color for the embed (decimal)"
    required: false
    default: "3066993"
  embed_fields:
    description: "Base64 Encoded JSON array of fields for the embed"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Validate Conflicted Fields Inputs
      if: inputs.embed_template != '' && inputs.message != ''
      shell: bash
      run: echo "::error::Cannot provide both 'embed_template' and 'message', Choose one!" && exit 1

    - name: Validate Required Inputs
      if: inputs.embed_template == '' && inputs.message == ''
      shell: bash
      run: echo "::error::Either 'message' or 'embed_template' is required" && exit 1

    - name: Decode Webhook
      shell: bash
      id: discord
      run: echo "DISCORD_WEBHOOK=$(echo "${{ inputs.discord_webhook }}" | base64 -d)" >> "$GITHUB_OUTPUT"

    - name: Process Embed Template
      if: inputs.embed_template != ''
      shell: bash
      id: embed
      env:
        EMBED_TITLE: ${{ inputs.embed_title }}
        EMBED_COLOR: ${{ inputs.embed_color }}
        EMBED_FIELDS: ${{ inputs.embed_fields }}
      run: |
        # echo -e "Title: ${{ inputs.embed_title }}\nColor: ${{ inputs.embed_color }}\nFields: ${{ inputs.embed_fields }}"
        FIELDS_JSON=$(echo "${{ inputs.embed_fields }}" | base64 -d)
        EMBED_JSON=$(jq -n \
          --arg title "$EMBED_TITLE" \
          --arg color "$EMBED_COLOR" \
          --argjson fields "$EMBED_FIELDS" \
          '{
            "embeds": [{
              "title": $title,
              "color": ($color | tonumber),
              "fields": $fields
            }]
          }')

        echo "PROCESSED_EMBED=$EMBED_JSON" >> "$GITHUB_OUTPUT"

    - name: Send Discord Message Using Embed Templates
      if: inputs.embed_template != ''
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ steps.discord.outputs.DISCORD_WEBHOOK }}
        DISCORD_EMBEDS: ${{ steps.embed.outputs.PROCESSED_EMBED }}

    - name: Send Discord Message
      if: inputs.message != ''
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ steps.discord.outputs.DISCORD_WEBHOOK }}
      with:
        args: |

          ======== MESSAGE START ========

          ${{ inputs.message }}

          ========  MESSAGE END  ========
